# -*- coding: utf-8 -*-
"""final_notebook_BA865 group project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FU8xfNemhRLsiEEX0NRfcDD_Qk6IxIjk

# Recycling with Deep Learning: A CNN-Based Approach to Waste Classification
### By : Ching Hsuan Lin, Kayla Candice Huang, Pin Hao Pan, Zhe Yu Lin

# Motivation

According to California Review Management, roughly 1.8 million acres of U.S. land are consumed by landfills, yet only 32.1 % of American waste is recycled or composted—mainly because contamination (mixing general trash or food-soiled items with recyclables) often renders whole batches unrecyclable, driving up greenhouse-gas emissions, polluting soil and groundwater, and forcing municipalities to spend more on manual sorting or rejected loads. To address this, we propose a fine-grained CNN-based image classifier that can be embedded in smart waste bins to automatically identify and guide proper disposal. Deployed in public spaces, campuses, industrial facilities, and residential complexes, this system pre-sorts materials at scale, cuts contamination, lowers operational costs, and ultimately strengthens urban recycling infrastructure for a smaller environmental footprint.

# Data Dictionary

| class_name     | description                                                               |
|----------------|---------------------------------------------------------------------------|
| General Waste  | Non-recyclable or contaminated items that cannot be composted or recycled. |
| Organic Waste  | Biodegradable, compostable materials of biological origin.                |
| Paper          | Clean, dry paper products free of plastic film, wax, or heavy contamination. |
| Plastic        | Rinse-clean plastic containers and products (labels removed when possible). |
| Glass          | Empty, rinse-clean glass bottles and jars (lids removed when possible).                 |
| Metal          | Rinse-clean metal cans and containers.            |

# Executive Summary

In this project, we set out to build an automated system for classifying everyday waste into six categories—General Waste, Organic, Paper, Plastic, Glass, and Metal—using deep learning. We began by collecting our own dataset of garbage images under real-world conditions, converting all photos to JPEG format at a uniform 224×224 resolution, and applying standard data augmentations (flips and rotations) to improve robustness.  

Our first approach was a custom convolutional neural network trained from scratch. We started with basic augmentations such as random flips, rotations, and zooms, and used three Conv2D layers with the RMSprop optimizer. Building on this structure, we also experimented with adding a fourth convolutional layer, incorporating dropout to prevent overfitting, and applying stronger augmentations like random translations to each self-constructed model.  

To leverage richer feature representations, we then turned to transfer learning. A ResNet50 model pre-trained on ImageNet produced more balanced predictions but uniformly low confidence scores across all classes—suggesting that, while it recognized differences, it could not decisively distinguish among our six waste types, resulting in lower test accuracy.  

Finally, we adopted MobileNetV2, a lightweight architecture better suited for small datasets. Without CutMix augmentation, our MobileNetV2 model already outperformed ResNet50 in overall validation accuracy and confidence. Introducing CutMix—where image patches and labels are mixed during training—further reduced misclassifications, particularly between visually similar classes like Plastic and Glass. In the end, we found that MobileNetV2 delivered the best performance.

#Data Preprocessing

Before we fed the images into our model, we went through a standardized preprocessing pipeline.  
1.First, we filtered the file formats by converting all images to JPEG, to avoid any hidden errors from inconsistent formats.  
2.Then, we corrected the orientation to make sure that sideways or upside-down photos wouldn't affect the model's learning.  
3.Next, we converted the images to RGB mode, removing any transparency issues that could interfere when saving as JPEG.  
4.After that, we resize all images—scaling them down if they were larger than 224 by 224 pixels but making sure not to upscale small ones.  
5.For non-square images, we centered them on a white background to maintain the correct aspect ratio without distortion.  
6.Finally, we unified the file names to standardize the dataset and make future processing more efficient.
"""

import tensorflow as tf
import numpy as np
import random

SEED = 100
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

# !pip install pyheif
import os
from PIL import Image, ImageOps

# Input and output folder paths — please update according to your actual setup
input_folder = "/content/drive/MyDrive/BA 865 Project/garbage_data/Recyclables_Plastic(114)"
output_folder = "/content/drive/MyDrive/BA 865 Project/garbage_data/Recyclables_Plastic(114)_1"
os.makedirs(output_folder, exist_ok=True)

counter = 1  # Initialize a counter starting from 1

for filename in os.listdir(input_folder):
    name, ext = os.path.splitext(filename)
    ext = ext.lower()

    # Process only files with .jpg or .jpeg extensions
    if ext not in [".jpg", ".jpeg"]:
        continue

    input_path = os.path.join(input_folder, filename)

    # Generate a new filename using the counter, e.g., Plastic_1.jpeg, Plastic_2.jpeg, ...
    new_filename = f"Plastic_{counter}.jpeg"
    output_path = os.path.join(output_folder, new_filename)

    try:
        image = Image.open(input_path)
        image = ImageOps.exif_transpose(image)  # Correct image orientation based on EXIF data
        image = image.convert("RGB")  # JPEG does not support transparency

        # Calculate scaling ratio without enlarging small images (scale only if larger than 224)
        old_w, old_h = image.size
        target_w, target_h = 224, 224
        ratio = min(1.0, min(target_w / old_w, target_h / old_h))
        new_w = int(old_w * ratio)
        new_h = int(old_h * ratio)
        resized = image.resize((new_w, new_h), Image.Resampling.LANCZOS)

        # Center the resized image on a white background (255, 255, 255)
        new_img = Image.new("RGB", (target_w, target_h), (255, 255, 255))
        left = (target_w - new_w) // 2
        top = (target_h - new_h) // 2
        new_img.paste(resized, (left, top))

        new_img.save(output_path, "JPEG")
        print(f"Success: {filename} → {new_filename}")

        counter += 1  # Increment counter after successful processing
    except Exception as e:
        print(f"Failed: {filename} failed: {e}")

print("Finished!")

"""# Train, Validation, Test Split"""

import os
import random
import shutil

# origial folder
source_folder = "/content/drive/MyDrive/BA 865 Project/garbage_data_converted/Recyclables_Plastic(114)_1"

# target folder
train_folder = "/content/drive/MyDrive/BA 865 Project/train/Plastic"
val_folder = "/content/drive/MyDrive/BA 865 Project/validation/Plastic"
test_folder = "/content/drive/MyDrive/BA 865 Project/test/Plastic"

# make sure all files are there
os.makedirs(train_folder, exist_ok=True)
os.makedirs(val_folder, exist_ok=True)
os.makedirs(test_folder, exist_ok=True)

# set the proportion
train_ratio = 0.7
val_ratio = 0.15
test_ratio = 0.15

# get all file paths
images = [f for f in os.listdir(source_folder) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
random.shuffle(images)

# count the amount of pictures
total = len(images)
train_end = int(total * train_ratio)
val_end = train_end + int(total * val_ratio)

# split the dataset
train_imgs = images[:train_end]
val_imgs = images[train_end:val_end]
test_imgs = images[val_end:]

# Copy images from the source folder to a specified destination folder
def copy_images(img_list, dest_folder):
    for img in img_list:
        src_path = os.path.join(source_folder, img)
        dst_path = os.path.join(dest_folder, img)
        shutil.copy(src_path, dst_path)


copy_images(train_imgs, train_folder)
copy_images(val_imgs, val_folder)
copy_images(test_imgs, test_folder)

print(f"Total: {total} images")
print(f"Train: {len(train_imgs)}, Validation: {len(val_imgs)}, Test: {len(test_imgs)}")

"""# Read the data"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from tensorflow.keras.utils import image_dataset_from_directory

base_dir = '/content/drive/MyDrive/BA 865 Project'

train_dataset = image_dataset_from_directory(
    base_dir + "/train/",
    image_size=(224, 224),
    batch_size=32)
validation_dataset = image_dataset_from_directory(
    base_dir + "/validation/",
    image_size=(224, 224),
    batch_size=32)

"""# Model Evaluation Function"""

!pip install lime

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from lime import lime_image
from skimage.segmentation import mark_boundaries
from tensorflow import keras

def explain_with_lime(
    model,
    img_path,
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
):

    # 1. Load and preprocess the image
    img = Image.open(img_path).convert('RGB')
    img = img.resize(image_size)
    x = np.array(img)

    # 2. Define prediction function for LIME
    def predict_fn(imgs):
        imgs = np.array(imgs).astype(np.float32) / 255.0
        return model.predict(imgs)

    # 3. Create a LIME image explainer and generate explanation
    explainer = lime_image.LimeImageExplainer()
    exp = explainer.explain_instance(
        image=x,
        classifier_fn=predict_fn,
        top_labels=top_labels,
        hide_color=hide_color,
        num_samples=num_samples
    )

    # 4. Get regions that positively contribute to the prediction
    label = exp.top_labels[0]
    temp, mask = exp.get_image_and_mask(
        label,
        positive_only=True,
        num_features=num_features,
        hide_rest=False
    )

    # 5. Plot original image and LIME explanation
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    axes[0].imshow(x)
    axes[0].set_title("Original")
    axes[0].axis("off")

    axes[1].imshow(mark_boundaries(temp / 255.0, mask))
    axes[1].set_title(f"LIME for class {label}")
    axes[1].axis("off")

    plt.tight_layout()
    return fig

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

def predict_and_plot(
    model,
    img_path,
    class_names,
    img_size=(224, 224),
    normalize=True
):

    # 1. Load and preprocess the image
    img = Image.open(img_path).convert("RGB")
    img_resized = img.resize(img_size)
    x = np.array(img_resized, dtype=np.float32)
    if normalize:
        x /= 255.0
    x = np.expand_dims(x, axis=0)  # Shape becomes (1, H, W, 3)

    # 2. Make prediction
    probs = model.predict(x)[0]     # Shape = (num_classes,)
    idx   = np.argmax(probs)
    label = class_names[idx]
    conf  = probs[idx]

    # 3. Plot the result
    fig = plt.figure(figsize=(4, 4))
    plt.imshow(img)
    plt.title(f"Predicted: {label}\nConfidence: {conf:.2%}")
    plt.axis("off")
    plt.tight_layout()

    return fig, label, conf

"""# Selfbuilt Model V1"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow import keras
from tensorflow.keras import layers


# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Rescale only once globally ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

# --- Apply preprocessing and optimize data pipeline ---
train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Standard augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2)
])

# --- Model definition ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Flatten()(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/bestv1.h5')

"""### Plot Accuracy Over Training in Training vs. Validation Sample"""

import matplotlib.pyplot as plt
plt.style.use('ggplot')

# Add plotting statements
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model1 Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""### Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model1 Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## Model V1 Evaluate"""

# Load any pre-trained model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/bestv1.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/bestv1.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224, 224),
    normalize=True
)

# Display the image
fig.show()

# If you want to use the prediction result in the code
print(f"Predicted Class: {pred_label}, Confidence: {confidence:.2%}")

"""# Selfbuilt Model v2"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow import keras
from tensorflow.keras import layers


# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Rescale only once globally ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

# --- Apply preprocessing and optimize data pipeline ---
train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Standard augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2)
])

# --- Model definition ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Flatten()(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/bestv2.h5')

"""### Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model2 Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""### Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model2 Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## Model V2 Evaluate"""

# Load any pre-trained model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/bestv2.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/bestv2.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224, 224),
    normalize=True
)

# Display the image
fig.show()

# If you want to use the prediction result in the code
print(f"Predicted Class: {pred_label}, Confidence: {confidence:.2%}")

"""# Selfbuilt Model V3"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow import keras
from tensorflow.keras import layers


# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Rescale only once globally ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

# --- Apply preprocessing and optimize data pipeline ---
train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Standard augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2)
])

# --- Model definition ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Flatten()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/bestv3.h5')

"""## Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model3 Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""## Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model3 Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## V3 Evaluate"""

# Load any pre-trained model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/bestv3.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/Paper_16.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/bestv3.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224, 224),
    normalize=True
)

# Display the image
fig.show()

# If you want to use the prediction result in the code
print(f"Predicted Class: {pred_label}, Confidence: {confidence:.2%}")

"""# Selfbuilt Model V4"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow import keras
from tensorflow.keras import layers


# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Rescale only once globally ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

# --- Apply preprocessing and optimize data pipeline ---
train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Standard augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2),
    layers.RandomTranslation(0.1, 0.1)
])

# --- Model definition ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=256, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Flatten()(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/bestv4.h5')

"""### Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model4 Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""### Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model4 Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## Model V4 Evaluate"""

# Load any pre-trained model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/bestv4.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/bestv4.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224, 224),
    normalize=True
)

# Display the image
fig.show()

# If you want to use the prediction result in the code
print(f"Predicted Class: {pred_label}, Confidence: {confidence:.2%}")

"""# Pretrained Model - ResNet50"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# --- Basic settings ---
IMG_SIZE    = 224
BATCH_SIZE  = 32
NUM_CLASSES = 6
AUTOTUNE    = tf.data.AUTOTUNE
base_dir    = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = keras.utils.image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = keras.utils.image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Preprocessing (/255) ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

train_dataset = (
    train_dataset_raw
    .map(preprocess_image)
    .cache()
    .shuffle(1000, seed=SEED)
    .prefetch(AUTOTUNE)
)

val_dataset = (
    val_dataset_raw
    .map(preprocess_image)
    .cache()
    .prefetch(AUTOTUNE)
)

# --- Data Augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2),
])

# --- Model definition with ResNet50 backbone + custom Conv head ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)

# 1) ResNet50 feature extractor
base_model = keras.applications.ResNet50(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)
base_model.trainable = False
x = base_model(x, training=False)

# 2) Conv2D + Pooling
x = layers.Conv2D(32, 3, padding="same", activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(64, 3, padding="same", activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(128, 3, padding="same", activation="relu")(x)
x = layers.GlobalAveragePooling2D()(x)

x = layers.Dense(128, activation="relu")(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/resnet50.h5')

"""## Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('ResNet50 Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""## Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('ResNet50 Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## ResNet50 Model Evaluation

"""

# Load any model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/resnet50.h5')

# Call the explanation function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/resnet50.h5"
CLASS_NAMES = ['General Waste','Glass','Metal','Organic Waste','Paper','Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the prediction function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224,224),
    normalize=True
)

# Display the figure
fig.show()

# Use the prediction result in the program
print(f"Predicted class: {pred_label}, Confidence: {confidence:.2%}")

"""# Pretrained Model - MobileNetV2 without cutmix"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# --- Load datasets ---
train_dataset_raw = keras.utils.image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = keras.utils.image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Preprocessing ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED).prefetch(AUTOTUNE)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Data Augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2),
])

# --- Model definition ---
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)

base_model = keras.applications.MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)
base_model.trainable = False

x = base_model(x, training=False)
x = layers.Conv2D(filters=32, kernel_size=3, padding="same",activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, padding="same",activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3 ,padding="same",activation="relu")(x)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)


model = keras.Model(inputs=inputs, outputs=outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    epochs=50,
    validation_data=val_dataset
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/mobilenetv2.h5')

"""## Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('MobileNetV2 Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""## Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('MobileNetV2 Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## MobileNetV2 Without CutMix Evaluation"""

# Load any model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/mobilenetv2.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/mobilenetv2.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load the model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224, 224),
    normalize=True
)

# Display the figure
fig.show()

# To use the prediction results in the program
print(f"Predicted Class: {pred_label}, Confidence: {confidence:.2%}")

"""# Pretrained Model - MobileNetV2 with CutMix"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import EarlyStopping

# --- Basic settings ---
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 6
AUTOTUNE = tf.data.AUTOTUNE
base_dir = "/content/drive/MyDrive/BA 865 Project"

# Accelerate data loading
train_dataset_raw = tf.keras.utils.image_dataset_from_directory(
    base_dir + "/train",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)
val_dataset_raw = tf.keras.utils.image_dataset_from_directory(
    base_dir + "/validation",
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# --- Preprocessing ---
def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

train_dataset = train_dataset_raw.map(preprocess_image).cache().shuffle(1000, seed=SEED).prefetch(AUTOTUNE)
val_dataset = val_dataset_raw.map(preprocess_image).cache().prefetch(AUTOTUNE)

# --- Data Augmentation ---
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.2),
])

# --- CutMix with sparse labels ---
def cutmix(image_batch, label_batch):
    batch_size = tf.shape(image_batch)[0]
    # 1. Shuffle within batch
    indices = tf.random.shuffle(tf.range(batch_size))
    shuffled_images = tf.gather(image_batch, indices)
    shuffled_labels = tf.gather(label_batch, indices)

    # 2. Sample mix ratio and box size
    lam = tf.random.uniform((), 0.3, 0.7)
    cut_rat = tf.math.sqrt(1 - lam)
    cut_w = tf.cast(IMG_SIZE * cut_rat, tf.int32)
    cut_h = tf.cast(IMG_SIZE * cut_rat, tf.int32)

    # 3. Random box center
    cx = tf.random.uniform((), 0, IMG_SIZE, dtype=tf.int32)
    cy = tf.random.uniform((), 0, IMG_SIZE, dtype=tf.int32)
    x1 = tf.clip_by_value(cx - cut_w // 2, 0, IMG_SIZE)
    y1 = tf.clip_by_value(cy - cut_h // 2, 0, IMG_SIZE)
    x2 = tf.clip_by_value(cx + cut_w // 2, 0, IMG_SIZE)
    y2 = tf.clip_by_value(cy + cut_h // 2, 0, IMG_SIZE)

    # 4. Create a binary mask of shape (batch, IMG_SIZE, IMG_SIZE, 3)
    patch = tf.ones((batch_size, y2-y1, x2-x1, 3), dtype=tf.float32)
    mask = tf.pad(patch,
                  [[0, 0],
                   [y1, IMG_SIZE - y2],
                   [x1, IMG_SIZE - x2],
                   [0, 0]])

    # 5. Mix images
    mixed_images = image_batch * (1 - mask) + shuffled_images * mask

    return mixed_images, label_batch

# Apply CutMix during training using a map function
train_dataset = train_dataset.map(cutmix, num_parallel_calls=AUTOTUNE)

# --- Model definition ---
base_model = MobileNetV2(input_shape=(IMG_SIZE, IMG_SIZE, 3), include_top=False, weights="imagenet")
base_model.trainable = False

inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = data_augmentation(inputs)
x = base_model(x, training=False)
x = layers.Conv2D(filters=32, kernel_size=3, padding="same", activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, padding="same", activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3 ,padding="same", activation="relu")(x)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = keras.Model(inputs, outputs)

# --- Compile model ---
model.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Model summary ---
model.summary()

# --- Training ---
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=50
)

# --- Save model ---
model.save('/content/drive/MyDrive/BA 865 Project/mobilenetv2_cutmix.h5')

"""## Plot Accuracy Over Training in Training vs. Validation Sample"""

plt.style.use('ggplot')

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('MobileNetV2 with Cutmix Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""## Plot Loss Over Training in Training vs. Validation Sample"""

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('MobileNetV2 with Cutmix Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## MobileNetV2 with CutMix Evaluation"""

# Load any model
model = keras.models.load_model('/content/drive/MyDrive/BA 865 Project/mobilenetv2_cutmix.h5')

# Call the function and display the result
fig = explain_with_lime(
    model,
    img_path=base_dir + '/test3.jpeg',
    image_size=(224, 224),
    top_labels=1,
    hide_color=0,
    num_samples=500,
    num_features=5
)
fig.show()

# Parameter settings
MODEL_PATH  = "/content/drive/MyDrive/BA 865 Project/mobilenetv2_cutmix.h5"
CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']
IMG_PATH    = "/content/drive/MyDrive/BA 865 Project/test3.jpeg"

# Load model
model = keras.models.load_model(MODEL_PATH)

# Call the function
fig, pred_label, confidence = predict_and_plot(
    model=model,
    img_path=IMG_PATH,
    class_names=CLASS_NAMES,
    img_size=(224,224),
    normalize=True
)

# Display the figure
fig.show()

# If you want to use the prediction result in the program
print(f"Predicted class: {pred_label}, Confidence: {confidence:.2%}")

"""# Test Set Evaluation"""

from tensorflow.keras.models import load_model
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

test_dataset = image_dataset_from_directory(
    base_dir + "/test/",
    image_size=(224, 224),
    batch_size=32,
    shuffle=False,
    seed=100
)

CLASS_NAMES = ['General Waste', 'Glass', 'Metal', 'Organic Waste', 'Paper', 'Plastic']

def preprocess_image(x, y):
    x = tf.cast(x, tf.float32) / 255.0
    return x, y

test_dataset = test_dataset.map(preprocess_image).cache().prefetch(tf.data.AUTOTUNE)

models = {
    'Self-Built1': load_model('/content/drive/MyDrive/BA 865 Project/bestv1.h5'),
    'Self-Built2': load_model('/content/drive/MyDrive/BA 865 Project/bestv2.h5'),
    'Self-Built3': load_model('/content/drive/MyDrive/BA 865 Project/bestv3.h5'),
    'Self-Built4': load_model('/content/drive/MyDrive/BA 865 Project/bestv4.h5'),
    'ResNet50': load_model('/content/drive/MyDrive/BA 865 Project/resnet50.h5'),
    'MobileNetV2': load_model('/content/drive/MyDrive/BA 865 Project/mobilenetv2.h5'),
    'MobileNetV2-cutmix': load_model('/content/drive/MyDrive/BA 865 Project/mobilenetv2_cutmix.h5')
}

for model_name, model in models.items():
    print(f"Evaluating {model_name}...")
    test_loss, test_accuracy = model.evaluate(test_dataset)
    print(f"{model_name} - Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

    y_true = []
    y_pred = []
    for images, labels in test_dataset:
        predictions = model.predict(images)
        y_true.extend(labels.numpy())
        y_pred.extend(np.argmax(predictions, axis=1))

    print(f"Classification Report for {model_name}:")
    print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))
    print(f"Confusion Matrix for {model_name}:")
    print(confusion_matrix(y_true, y_pred))

"""# Suggestions and Future Works

Looking ahead, we plan to take several steps to improve our model’s performance:

1. Multi-Object Recognition  
Extend the classifier so it can detect and label multiple waste types within a single image — enabling it to handle complex scenes like mixed recycling bins.
2. Real-Time Edge Inference  
Integrate OpenCV to capture live video frames, then deploy a quantized version of our model on edge devices (e.g. Raspberry Pi). This will deliver low-latency, on-device predictions for instant waste sorting.
3. Expanded Data Collection  
Gather a larger, more diverse dataset — covering different lighting conditions, backgrounds, and waste arrangements — to improve generalization and reduce overfitting.
4. Transformer-Based Architectures  
Experiment with vision transformers such as ViT and DeiT, which have outperformed CNNs on many classification benchmarks. Fine-tuning these models could unlock additional accuracy gains.
5. Model Ensembles  
Combine the top-performing architectures (e.g. MobileNetV2 + CutMix, fine-tuned ResNet50, EfficientNet-Lite) via simple averaging or weighted voting to stabilize and often improve overall accuracy.
"""